version: "3.7"

services:
    # image project
    app:
        container_name: emonitor-app
        build:
            context: .
            dockerfile: Dockerfile
        image: tsnetwork/emonitor
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - e-monitor

    # nginx
    nginx:
        container_name: emonitor-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8002:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - e-monitor

    # db mysql
    mysql:
        container_name: emonitor-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: emonitor
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - e-monitor

    # queue
    queue:
        container_name: emonitor-queue
        image: tsnetwork/emonitor
        restart: unless-stopped
        command: "php artisan horizon"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - e-monitor
    # schedule
    schedule:
        container_name: emonitor-schedule
        image: tsnetwork/emonitor
        restart: unless-stopped
        command: "php artisan schedule:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - e-monitor

    # redis
    redis:
        container_name: emonitor-redis
        image: redis:latest
        networks:
            - e-monitor

networks:
    e-monitor:
        driver: bridge
